### ISSUE TITLE
Access relative to supply

### ISSUE THREAD

**Issue by nkrabben** [hadro/hathi_analysis#1]
I'd be interested in seeing how the top40k items represent access proportional to the amount of material in hathi. Some pseudoish code to explain it.
```
df = pd.DataFrame(data, columns = ['year', 'items_in_top40', 'items_in_hathi', 'items_open])

df['rel_total'] = df.items_in_top_40/df.items_in_hathi
df.plot(x = 'year', y = rel_total, type = 'scatter')

df['rel_open'] = df.items_in_top_40/df.items_open
df.plot(x = 'year', y = rel_open, type = 'scatter')
```

**Comment by hadro** [comment]
I believe we fixed this up with the tweaks to this graph: 
https://hadro.github.io/hathi_analysis/percentage_years.html
