### ISSUE TITLE
Comparison of CCE to HT

### ISSUE THREAD

**Issue by gregcram** [hadro/hathi_analysis#3]
As a user, I would like to compare the number of CCE registrations for books published in the US with HT's data of US published books so that I can determine whether CCE registrations are a good representation for all books published in the US for a particular time.

I have book registration data for 1923-1952 (1953-onward includes non-book type registrations).

AC1: For each year from 1923 to 1952, please count the number of unique titles in HT. 

`select count(distinct(hathitrust_record_number)) from hathifiles where (publication_date = '1949' or publication_date = '1949.0') and bibliograhic_format = 'BK' and publication_place LIKE '__u' `

`select count(distinct(oclc_number)) from hathifiles where (publication_date = '1949' or publication_date = '1949.0') and bibliograhic_format = 'BK' and publication_place LIKE '__u' `

**Comment by hadro** [comment]
Can be refined down the road, but the initial analysis for this is here: 
https://hadro.github.io/hathi_analysis/cce_count.html
