### ISSUE TITLE
Add in the usage

### ISSUE THREAD

**Issue by nkrabben** [hadro/hathi_analysis#4]
It would be good to see if there are relationships between publication year and usage amount on a volume level. This might need some binning to be useful.

Quick sketch
Axis 1: Years, maybe binned into decades or centuries
Axis 2: Access level, binned into ... 0, 1, 2-5, 6-20, ... 1,000-1,000,000 (not really sure about the bins)
Axis 3: Either number of volumes in year/access bin, or percentage of volumes in year/access bin compared to that entire year's volumes

**Comment by nkrabben** [comment]
For axis 2, maybe binning by power's of 10
0, 1, 2-10, 11-100, 101-1000, 1001-10000, 10001-100000, 100001-1000000

**Comment by hadro** [comment]
Pretty sure I did this here, though not with the binning approach you suggested: https://hadro.github.io/hathi_analysis/usage_heatmap.html
